### ISSUE TITLE
Add example configuration to do JWT AT validation

### ISSUE THREAD

**Issue by ggallard** [Identicum/oauth-demoapi-spring#2]
To prevent calling the introspect_endpoint when the AT is a JWT.

[docs](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver-jwt-jwkseturi
)

```
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.example.com
          jwk-set-uri: https://idp.example.com/.well-known/jwks.json
```
